version: "3"

services:
  node_api:
    image: node_api
    container_name: node_api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    networks:
      - gateway
    ports:
      - "3000:3000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=node-api"
      - "traefik.backend.port=3000"
      - "traefik.http.routers.node_api.rule=Host(`api.node.localhost`)"
      - "traefik.http.services.node_api.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.node_api.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.node_api.loadbalancer.healthcheck.path=/health"
      - "traefik.frontend.rule=Host:api.node.localhost"
      - "traefik.port=3000"
      - "traefik.docker.network=gateway"
  
  node_traefik:
    image: node_traefik
    container_name: node_traefik
    build:
      context: .
      dockerfile: ./docker/traefik/Dockerfile
    command: --web --docker --docker.domain=node.localhost --docker.exposedbydefault=false --logLevel=DEBUG --configFile=/etc/traefik/traefik.toml
    networks:
        - gateway
        - traefik
    ports:
        - "80:80"
        - "8080:8080"
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./docker/traefik/traefik.toml:/traefik.toml

networks:
  gateway:
    external: true
  traefik:
    external: true