version: "3"

services:
  node_api:
    image: node_api
    container_name: node_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - gateway
      - traefik
    ports:
      - "8000:8000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=node-api"
      - "traefik.backend.port=8000"
      - "traefik.http.routers.node_api.rule=Host(`node.docker.localhost`)"
      - "traefik.http.services.node_api.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.node_api.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.node_api.loadbalancer.healthcheck.path=/health"
      - "traefik.frontend.rule=Host:node.docker.localhost"
      - "traefik.port=8000"
      - "traefik.docker.network=gateway"

networks:
  gateway:
    external: true
  traefik:
    external: true