version: '3'
services:
  node-api:
    image: node-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - gateway
    ports:
      - "3000:3000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=node-api"
      - "traefik.backend.port=3000"
      - "traefik.http.routers.node-api.rule=Host(`node.localhost`)"
      - "traefik.http.services.node-api.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.node-api.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.node-api.loadbalancer.healthcheck.path=/health"
      - "traefik.frontend.rule=Host:node.localhost"
      - "traefik.port=3000"
      - "traefik.docker.network=gateway"
  
  node-traefik:
    image: traefik:1.7.21-alpine
    command: --web --docker --docker.domain=node.localhost --docker.exposedbydefault=false --logLevel=DEBUG --configFile=/etc/traefik/traefik.toml
    networks:
        - gateway
    ports:
        - "80:80"
        - "8080:8080"
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./docker/traefik/traefik.toml:/traefik.toml

networks:
  gateway:
    external: true