defaultEntryPoints = ["http"]
logLevel = "DEBUG"

[api]
address = ":8080"

[entryPoints]
    [entryPoints.http]
    address = ":80"

[ping]
    entryPoint = "http"

[retry]
attempts = 3
maxMem = 3

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "node.localhost"
network = "gateway"
watch = true
exposedbydefault = false